### ISSUE TITLE
Migrate policy not firing

### ISSUE THREAD

**Issue by cgbaker** [GalacticFog/gestalt-policy#2]
Meta seems to be sending the event and policy seems to be catching it, but then it's hitting a MethodNotImplemented and I think the whole service is coming down. Except maybe the /health endpoint? 

Anyway, if I manually restart the service in Marathon and then hit `/` to wake it up, it immediately hits rabbit, gets the previous events from the bus, and then fails again. Log output looks like this: 

> [[36mdebug[0m] application - newBinderActor(( b4f900a2-5095-410f-b3a6-903c9d095a55 )
[[36mdebug[0m] application - preStart( b4f900a2-5095-410f-b3a6-903c9d095a55 )
[[36mdebug[0m] application - RepopulateMap
[[36mdebug[0m] application - preStart( 888d792e-7222-4580-9a1a-0956115a40c3 )
[[36mdebug[0m] application - preStart( de9ac52b-0bed-4d2d-b931-cf7eccc94ed5 )
[[36mdebug[0m] application - preStart( db8473e6-250d-4b46-bac4-1081d27e2779 )
[[36mdebug[0m] application - incoming event : {"eventContext":{"eventName":"container.migrate","meta":"http://meta.dev.galacticfog.com","workspace":"0504a473-f33c-47bc-91e7-d59e3a329ae1","environment":"e2ce2d72-658a-4b63-81c2-0782d899a09b","org":"19beb1bc-058d-4754-bcfc-b3f0550d9845","resourceId":"03794ddf-b2af-41da-85c0-7d4b9d641753","resourceType":""},"lambdaArgs":{"resource":{"id":"03794ddf-b2af-41da-85c0-7d4b9d641753","typeId":"28cbf0e0-2c48-4589-85d5-df97a3a1f318","state":"cb132708-fb29-4b73-ba38-b199400f48da","orgId":"19beb1bc-058d-4754-bcfc-b3f0550d9845","owner":{"typeId":"58b6775d-37a5-44bc-9115-7331fc4964b7","id":"0a6ab5e7-0c17-4a7a-adc5-0ea98a6b832c","name":"root","href":"/orgs/c6ce5cee-4f84-417c-80c3-a860c8c4e9cf/users/0a6ab5e7-0c17-4a7a-adc5-0ea98a6b832c"},"name":"good-container","created":{"typeId":"58b6775d-37a5-44bc-9115-7331fc4964b7","id":"0a6ab5e7-0c17-4a7a-adc5-0ea98a6b832c","timestamp":"2016-04-15T16:51:34.071Z"},"modified":{"action":"update","user":"0a6ab5e7-0c17-4a7a-adc5-0ea98a6b832c","timestamp":"2016-04-16T20:20:09.754Z"},"properties":{"network":"BRIDGE","num_instances":"1","provider":"{\"id\":\"9282109f-ed60-43bb-9517-eb4f65b9ed59\",\"name\":\"v2_gfi\"}","tasks_healthy":"0","image":"nginx","tasks_running":"1","force_pull":"false","age":"2016-04-15T16:51:33.938Z","container_type":"DOCKER","workspace":"0504a473-f33c-47bc-91e7-d59e3a329ae1","tasks_staged":"0","status":"RUNNING","tasks_unhealthy":"0","fqon":"galacticfog.engineering","external_id":"/galacticfog.engineering/chris-space/dev/good-container","cpus":"0.2","environment_type":"0d79607d-46b6-47f4-b455-961e7bc2481d","port_mappings":"[]","memory":"128"},"variables":{},"tags":[]},"rule":{"id":"1a79ab3c-be3b-4261-b09b-c822e53033f7","typeId":"55fc08d0-2593-43a1-9a65-cbdb00e5ac52","state":"cb132708-fb29-4b73-ba38-b199400f48da","orgId":"19beb1bc-058d-4754-bcfc-b3f0550d9845","owner":{"typeId":"58b6775d-37a5-44bc-9115-7331fc4964b7","id":"0a6ab5e7-0c17-4a7a-adc5-0ea98a6b832c","name":"root","href":"/orgs/c6ce5cee-4f84-417c-80c3-a860c8c4e9cf/users/0a6ab5e7-0c17-4a7a-adc5-0ea98a6b832c"},"name":"migrate","description":"","created":{"typeId":"58b6775d-37a5-44bc-9115-7331fc4964b7","id":"0a6ab5e7-0c17-4a7a-adc5-0ea98a6b832c","timestamp":"2016-04-15T22:13:12.226Z"},"modified":{"action":"created","typeId":"58b6775d-37a5-44bc-9115-7331fc4964b7","id":"0a6ab5e7-0c17-4a7a-adc5-0ea98a6b832c","timestamp":"2016-04-15T22:13:12.226Z"},"properties":{"parent":"1b0fa052-c88f-41d8-886e-9e34fd3b0d78","defined_at":"{\"typeId\":\"46b28076-9d94-4860-9aca-e8483a56d32c\",\"id\":\"e2ce2d72-658a-4b63-81c2-0782d899a09b\",\"name\":\"dev\",\"href\":\"http://meta.dev.galacticfog.com/orgs/19beb1bc-058d-4754-bcfc-b3f0550d9845/environments/e2ce2d72-658a-4b63-81c2-0782d899a09b\"}","lambda":"14e87f2a-2424-44f6-b3d6-c54ef3a453e1","eval_logic":"{\\\"extraLogic\\\": \\\"whatever\\\"}","actions":"[\"container.migrate\"]"},"tags":[]}},"providerId":"5a850db0-1974-46dc-bb06-8fd407e464a7","metaUrl":"http://meta.dev.galacticfog.com"}
[[36mdebug[0m] application - preStart( 18d2050e-23d9-462a-aca5-ac2bcae5499b )
[[36mdebug[0m] application - preStart( c02051a4-6532-4f24-86ee-5af3437beb4a )
[[36mdebug[0m] application - incoming event : {"eventContext":{"eventName":"container.migrate","meta":"http://meta.dev.galacticfog.com","workspace":"0504a473-f33c-47bc-91e7-d59e3a329ae1","environment":"e2ce2d72-658a-4b63-81c2-0782d899a09b","org":"19beb1bc-058d-4754-bcfc-b3f0550d9845","resourceId":"5e3be7ab-a391-42a0-b224-e4bfca99b707","resourceType":""},"lambdaArgs":{"resource":{"id":"5e3be7ab-a391-42a0-b224-e4bfca99b707","typeId":"28cbf0e0-2c48-4589-85d5-df97a3a1f318","state":"cb132708-fb29-4b73-ba38-b199400f48da","orgId":"19beb1bc-058d-4754-bcfc-b3f0550d9845","owner":{"typeId":"58b6775d-37a5-44bc-9115-7331fc4964b7","id":"0a6ab5e7-0c17-4a7a-adc5-0ea98a6b832c","name":"root","href":"/orgs/c6ce5cee-4f84-417c-80c3-a860c8c4e9cf/users/0a6ab5e7-0c17-4a7a-adc5-0ea98a6b832c"},"name":"cli-example-server","created":{"typeId":"58b6775d-37a5-44bc-9115-7331fc4964b7","id":"0a6ab5e7-0c17-4a7a-adc5-0ea98a6b832c","timestamp":"2016-04-15T16:17:45.290Z"},"modified":{"action":"update","user":"0a6ab5e7-0c17-4a7a-adc5-0ea98a6b832c","timestamp":"2016-04-17T13:10:23.095Z"},"properties":{"network":"BRIDGE","num_instances":"1","provider":"{\"id\":\"9282109f-ed60-43bb-9517-eb4f65b9ed59\",\"name\":\"v2_gfi\"}","tasks_healthy":"1","image":"nginx","tasks_running":"1","health_checks":"[{\"protocol\":\"HTTP\",\"path\":\"/\",\"grace_period_seconds\":30,\"interval_seconds\":3,\"timeout_seconds\":20,\"max_consecutive_failures\":10}]","force_pull":"false","age":"2016-04-15T16:29:41.007Z","container_type":"DOCKER","workspace":"0504a473-f33c-47bc-91e7-d59e3a329ae1","tasks_staged":"0","status":"HEALTHY","tasks_unhealthy":"0","fqon":"galacticfog.engineering","external_id":"/galacticfog.engineering/chris-space/dev/cli-example-server","cpus":"0.1","environment_type":"0d79607d-46b6-47f4-b455-961e7bc2481d","port_mappings":"[{\"protocol\":\"tcp\",\"container_port\":80,\"host_port\":0,\"service_port\":0,\"label\":\"0\"}]","memory":"128"}},"rule":{"id":"1a79ab3c-be3b-4261-b09b-c822e53033f7","typeId":"55fc08d0-2593-43a1-9a65-cbdb00e5ac52","state":"cb132708-fb29-4b73-ba38-b199400f48da","orgId":"19beb1bc-058d-4754-bcfc-b3f0550d9845","owner":{"typeId":"58b6775d-37a5-44bc-9115-7331fc4964b7","id":"0a6ab5e7-0c17-4a7a-adc5-0ea98a6b832c","name":"root","href":"/orgs/c6ce5cee-4f84-417c-80c3-a860c8c4e9cf/users/0a6ab5e7-0c17-4a7a-adc5-0ea98a6b832c"},"name":"migrate","description":"","created":{"typeId":"58b6775d-37a5-44bc-9115-7331fc4964b7","id":"0a6ab5e7-0c17-4a7a-adc5-0ea98a6b832c","timestamp":"2016-04-15T22:13:12.226Z"},"modified":{"action":"created","typeId":"58b6775d-37a5-44bc-9115-7331fc4964b7","id":"0a6ab5e7-0c17-4a7a-adc5-0ea98a6b832c","timestamp":"2016-04-15T22:13:12.226Z"},"properties":{"parent":"1b0fa052-c88f-41d8-886e-9e34fd3b0d78","defined_at":"{\"typeId\":\"46b28076-9d94-4860-9aca-e8483a56d32c\",\"id\":\"e2ce2d72-658a-4b63-81c2-0782d899a09b\",\"name\":\"dev\",\"href\":\"http://meta.dev.galacticfog.com/orgs/19beb1bc-058d-4754-bcfc-b3f0550d9845/environments/e2ce2d72-658a-4b63-81c2-0782d899a09b\"}","lambda":"14e87f2a-2424-44f6-b3d6-c54ef3a453e1","eval_logic":"{\\\"extraLogic\\\": \\\"whatever\\\"}","actions":"[\"container.migrate\"]"},"tags":[]}},"providerId":"5a850db0-1974-46dc-bb06-8fd407e464a7","metaUrl":"http://meta.dev.galacticfog.com"}
[[36mdebug[0m] application - Env Map (
[[36mdebug[0m] application - 	( dd1495de-2428-416b-a56b-d24455d8b017.8dcb46b8-7d75-4c52-932c-5de8c6298c99.Lambda.Delete -> aadfffea-0f6c-4ab9-939f-d07990a27547 )
[[36mdebug[0m] application - 	( dd1495de-2428-416b-a56b-d24455d8b017.8dcb46b8-7d75-4c52-932c-5de8c6298c99.Lambda.Create -> aadfffea-0f6c-4ab9-939f-d07990a27547 )
[[36mdebug[0m] application - 	( af617b9b-19df-4c7c-88a5-b9e1ad2ed798.66a3fe4d-c65e-4682-9bf8-e37a622abb53.lambda.changed -> 80b5c4b6-970f-4560-ab09-caab1b78d11a )
[[36mdebug[0m] application - 	( b60cd8d2-9908-42e5-8b86-a99aa18dad2d.9cd62639-6453-4f2f-a433-10cf752881c3.lambda.precreate -> 57616f9e-a021-4eef-8587-454bdfd615da )
[[36mdebug[0m] application - 	( b60cd8d2-9908-42e5-8b86-a99aa18dad2d.9cd62639-6453-4f2f-a433-10cf752881c3.container.migrate -> 57616f9e-a021-4eef-8587-454bdfd615da )
[[36mdebug[0m] application - 	( dd1495de-2428-416b-a56b-d24455d8b017.8dcb46b8-7d75-4c52-932c-5de8c6298c99.Container.Create -> aadfffea-0f6c-4ab9-939f-d07990a27547 )
[[36mdebug[0m] application - 	( af617b9b-19df-4c7c-88a5-b9e1ad2ed798.66a3fe4d-c65e-4682-9bf8-e37a622abb53.lambda.postcreate -> 80b5c4b6-970f-4560-ab09-caab1b78d11a )
[[36mdebug[0m] application - 	( dd1495de-2428-416b-a56b-d24455d8b017.8dcb46b8-7d75-4c52-932c-5de8c6298c99.Container.PreCreate -> aadfffea-0f6c-4ab9-939f-d07990a27547 )
[[36mdebug[0m] application - 	( dd1495de-2428-416b-a56b-d24455d8b017.8dcb46b8-7d75-4c52-932c-5de8c6298c99.Lambda.PreCreate -> aadfffea-0f6c-4ab9-939f-d07990a27547 )
[[36mdebug[0m] application - 	( dd1495de-2428-416b-a56b-d24455d8b017.8dcb46b8-7d75-4c52-932c-5de8c6298c99.Lambda.PostDelete -> aadfffea-0f6c-4ab9-939f-d07990a27547 )
[[36mdebug[0m] application - 	( af617b9b-19df-4c7c-88a5-b9e1ad2ed798.66a3fe4d-c65e-4682-9bf8-e37a622abb53.lambda.delete -> 80b5c4b6-970f-4560-ab09-caab1b78d11a )
[[36mdebug[0m] application - 	( dd1495de-2428-416b-a56b-d24455d8b017.8dcb46b8-7d75-4c52-932c-5de8c6298c99.Lambda.PostCreate -> aadfffea-0f6c-4ab9-939f-d07990a27547 )
[[36mdebug[0m] application - 	( af617b9b-19df-4c7c-88a5-b9e1ad2ed798.66a3fe4d-c65e-4682-9bf8-e37a622abb53.lambda.precreate -> 80b5c4b6-970f-4560-ab09-caab1b78d11a )
[[36mdebug[0m] application - 	( b60cd8d2-9908-42e5-8b86-a99aa18dad2d.9cd62639-6453-4f2f-a433-10cf752881c3.lambda.create -> 57616f9e-a021-4eef-8587-454bdfd615da )
[[36mdebug[0m] application - )
[[36mdebug[0m] application - Workspace Map (
[[36mdebug[0m] application - 	( af617b9b-19df-4c7c-88a5-b9e1ad2ed798.40a34fc0-5d28-4e6e-ad5e-d569c750d82c.Container.Create -> 57616f9e-a021-4eef-8587-454bdfd615da )
[[36mdebug[0m] application - 	( b60cd8d2-9908-42e5-8b86-a99aa18dad2d.5b341a52-5c72-4ce0-839d-aa9ed4401c82.lambda.delete -> 57616f9e-a021-4eef-8587-454bdfd615da )
[[36mdebug[0m] application - 	( b60cd8d2-9908-42e5-8b86-a99aa18dad2d.5b341a52-5c72-4ce0-839d-aa9ed4401c82.container.precreate -> 57616f9e-a021-4eef-8587-454bdfd615da )
[[36mdebug[0m] application - 	( af617b9b-19df-4c7c-88a5-b9e1ad2ed798.40a34fc0-5d28-4e6e-ad5e-d569c750d82c.Container.PreCreate -> 57616f9e-a021-4eef-8587-454bdfd615da )
[[36mdebug[0m] application - 	( b60cd8d2-9908-42e5-8b86-a99aa18dad2d.5b341a52-5c72-4ce0-839d-aa9ed4401c82.container.migrate -> 57616f9e-a021-4eef-8587-454bdfd615da )
[[36mdebug[0m] application - )
[[36mdebug[0m] application - postStop( 888d792e-7222-4580-9a1a-0956115a40c3 )
[ERROR] [04/18/2016 02:04:07.099] [PolicyActorSystem-akka.actor.default-dispatcher-4] [LocalActorRefProvider(akka://PolicyActorSystem)] guardian failed, shutting down system
scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
	at com.galacticfog.gestalt.policy.actors.InvokeActor$$anonfun$1.applyOrElse(InvokeActor.scala:59)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at com.galacticfog.gestalt.policy.actors.InvokeActor.aroundReceive(InvokeActor.scala:14)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [04/18/2016 02:04:07.100] [PolicyActorSystem-akka.actor.default-dispatcher-4] [akka://PolicyActorSystem/user] an implementation is missing
scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
	at com.galacticfog.gestalt.policy.actors.InvokeActor$$anonfun$1.applyOrElse(InvokeActor.scala:59)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at com.galacticfog.gestalt.policy.actors.InvokeActor.aroundReceive(InvokeActor.scala:14)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[[36mdebug[0m] application - postStop( 18d2050e-23d9-462a-aca5-ac2bcae5499b )
[[36mdebug[0m] application - postStop( de9ac52b-0bed-4d2d-b931-cf7eccc94ed5 )
[[36mdebug[0m] application - postStop( c02051a4-6532-4f24-86ee-5af3437beb4a )
[[36mdebug[0m] application - postStop( db8473e6-250d-4b46-bac4-1081d27e2779 )
[DEBUG] [04/18/2016 02:04:07.117] [PolicyActorSystem-akka.actor.default-dispatcher-10] [EventStream] shutting down: StandardOutLogger started

**Comment by bradfutch** [comment]
Apologies for the not implemented error message, but the error is "Lambda not found".  in looking a little deeper at it the meta context for this event appears to be : 

"eventContext": {
    "eventName": "container.migrate",
    "meta": "http://meta.dev.galacticfog.com",
    "workspace": "0504a473-f33c-47bc-91e7-d59e3a329ae1",
    "environment": "e2ce2d72-658a-4b63-81c2-0782d899a09b",
    "org": "19beb1bc-058d-4754-bcfc-b3f0550d9845",
    "resourceId": "03794ddf-b2af-41da-85c0-7d4b9d641753",
    "resourceType": ""
  }

That org does not exist in meta.dev2 which is the only meta instance configured to work with the policy service right now.  If you want to configure it to point at the regular dev instance we will need to confirm with sy that the appropriate code is there to support policy. 

In any case, using the dev2 instance of meta for your context should help.  I've also restarted the dev policy instance to a version that implements that message with some more helpful information.
